package types.paths;
import elements.SvgElement;
import types.Path;
import visitors.PathVisitor;
/** 
* @module ClosePath.java
* @version 1.0 
* @since 2013-04-23
* @author Jimmy Lin (u5223173) - u5223173@uds.anu.edu.au
* 
* Edited by MacVim
* Class Info auto-generated by Snippet 
*/
public class ClosePath extends Path {
    
    public ClosePath (SvgElement e, String command, double[] points) {
        super(e);
    }
    // visitor pattern implementation
    public void acceptPV (PathVisitor visitor) {
        visitor.visitClosePath(this);
    }

    public String toString () {
        String str = "Close Path: \n";
        str += "\t command: " + this.command; 
        return str;
    }
    
}
