/** 
* @file RPS.c 
* @version 1.0
* @since 2013-03-20
* @author Jimmy Lin (u5223173) - u5223173@uds.anu.edu.au
*
* Edited by MacVim
* Info auto-generated by Snippet 
* */

#include <stdio.h>
#include <stdlib.h>
#define random(x) (rand()%x)
int main()
{
    char * input;
    int comp, user;
    int userScore = 0, compScore = 0;
    int enter = 0;
    printf("Game Started. Press 'n' for exit..\n");
    while (1) {
        // avoid the trick
        comp = random(3);
        // acquire input from user
        if (enter == 0){ // not the last character
            printf("\nRock, Paper, Sizers. Enter one of: 'r', 'p', 's' %% ");
        } else {
            enter = 0;
        }
        scanf("%c", input);
        // interpret the input - user selection
        if ( *input == 'n') {
            break; //exit of the program
        } else if ( *input == 'r'){
            printf("You selected: Rock    ");
            user = 0;
        } else if ( *input == 'p'){
            printf("You selected: Paper    ");
            user = 1;
        } else if ( *input == 's'){
            printf("You selected: Sizers    ");
            user = 2;
        } else {
            if ( enter == 0)  enter = 1; 
            continue;
        }
        // interpret the computer's selection
        if ( comp == 0 ) {
            printf("Computer selected: Rock\n");
        } else if ( comp == 1 ) {
            printf("Computer selected: Paper\n");
        } else if ( comp == 2 ) {
            printf("Computer selected: Sizers\n");
        }

        // determine the winning and loss
        if ( comp == user) {
            printf("Draw.\n");
        } else if ( comp == user + 1 || user == comp + 2) {
            printf("Computer Wins :) \n");
            compScore += 1;
        } else if ( user == comp + 1 || comp == user + 2 ) {
            printf("You Wins :( \n");
            userScore += 1;
        }

        // output the score of two sides
        printf("Your score: %d    Computer: %d \n", userScore, compScore);
    
    }

}

