%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Homework 06: LU with Partial Pivoting (overwrite L and A)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Copyright 2014 The University of Texas at Austin
%
% For licensing information see
%                http://www.cs.utexas.edu/users/flame/license.html 
%                                                                                 
% Programmed by: Jimmy Lin
%                jimmylin@utexas.edu
function [ A_out, L_out, p_out ] = LU_pp_unb_var1( A, L, p )
  [ ATL, ATR, ...
    ABL, ABR ] = FLA_Part_2x2( A, ...
                               0, 0, 'FLA_TL' );
  [ LTL, LTR, ...
    LBL, LBR ] = FLA_Part_2x2( L, ...
                               0, 0, 'FLA_TL' );
  [ pT, ...
    pB ] = FLA_Part_2x1( p, ...
                         0, 'FLA_TOP' );
  while ( size( ATL, 1 ) < size( A, 1 ) )
    [ A00,  a01,     A02,  ...
      a10t, alpha11, a12t, ...
      A20,  a21,     A22 ] = FLA_Repart_2x2_to_3x3( ATL, ATR, ...
                                                    ABL, ABR, ...
                                                    1, 1, 'FLA_BR' );
    [ L00,  l01,      L02,  ...
      l10t, lambda11, l12t, ...
      L20,  l21,      L22 ] = FLA_Repart_2x2_to_3x3( LTL, LTR, ...
                                                     LBL, LBR, ...
                                                     1, 1, 'FLA_BR' );
    [ p0, ...
      pi1, ...
      p2 ] = FLA_Repart_2x1_to_3x1( pT, ...
                                    pB, ...
                                    1, 'FLA_BOTTOM' );
    %------------------------------------------------------------%
    [ ~ , pi1 ] = max ([alpha11; a21]);
    if pi1 ~= 1,
        P = eye(size(A22)+[1 1]);
        P(1, 1) = 0; P(1, pi1) = 1;
        P(pi1, pi1) = 0; P(pi1, 1) = 1;
        new = P * [l10t, alpha11, a12t; L20, a21, A22];
        sep_col = size(ATL, 2);
        l10t = new(1, 1:sep_col);
        alpha11 = new(1, sep_col+1);
        a12t = new(1, (sep_col+2):end);
        L20 = new(2:end, 1:sep_col);
        a21 = new(2:end, sep_col+1);
        A22 = new(2:end, (sep_col+2):end);
    end
    l21 = a21 / alpha11;
    A22 = A22 - l21 * a12t;
    a21(:) = 0; lambda11 = 1;
    %------------------------------------------------------------%
    [ ATL, ATR, ...
      ABL, ABR ] = FLA_Cont_with_3x3_to_2x2( A00,  a01,     A02,  ...
                                             a10t, alpha11, a12t, ...
                                             A20,  a21,     A22, ...
                                             'FLA_TL' );
    [ LTL, LTR, ...
      LBL, LBR ] = FLA_Cont_with_3x3_to_2x2( L00, zeros(size(l01)), zeros(size(L02)),  ...
                                             l10t, lambda11, zeros(size(l12t)), ...
                                             L20,  l21,      L22, ...
                                             'FLA_TL' );
    [ pT, ...
      pB ] = FLA_Cont_with_3x1_to_2x1( p0, ...
                                       pi1, ...
                                       p2, ...
                                       'FLA_TOP' );
  end
  A_out = [ ATL, ATR
            ABL, ABR ];
  L_out = [ LTL, LTR
            LBL, LBR ];
  p_out = [ pT
            pB ];
return
