/**##############################################################
## MODULE: fib.c
## VERSION: 2.0 
## SINCE: 2013-09-11
## AUTHOR: Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
##         Bochao Zhan () - 
## DESCRIPTION: 
##      Generate the number in certain position of Fib sequence.
#################################################################
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <ctype.h>
#include <signal.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <errno.h>

#define false 0
#define true 1

const int MAX = 13;

static void doFib(int n, int doPrint);

/*
 * unix_error - unix-style error routine.
 */
inline static void 
unix_error(char *msg)
{
    fprintf(stdout, "%s: %s\n", msg, strerror(errno));
    exit(1);
}


int main(int argc, char **argv)
{
  int arg;
  int print;

  if(argc != 2){
    fprintf(stderr, "Usage: fib <num>\n");
    exit(-1);
  }

  if(argc >= 3){
    print = 1;
  }

  arg = atoi(argv[1]);
  if(arg < 0 || arg > MAX){
    fprintf(stderr, "number must be between 0 and %d\n", MAX);
    exit(-1);
  }

  doFib(arg, true);
  return 0;
}

/* 
 * Recursively compute the specified number. If print is
 * true, print it. Otherwise, provide it to my parent process.
 *
 * NOTE: The solution must be recursive and it must fork
 * a new child for each call. Each process should call
 * doFib() exactly once.
 */
static void 
doFib(int n, int doPrint)
{
    int status1, status2;
    if (n == 0 || n == 1) {
        // printf("%d\n", n);
        if (doPrint) {
            printf("%d\n", n);
            return ;
        } else
            exit(n);
    }
    // create a new process
    int child1 = fork(), child2;
    if (child1) child2 = fork();

    // No need for the input check since the argument is verified
    // in the main() function.
    if (child1 == 0) {
        // Child Process:
        doFib(n - 1, false);
    } else if (child2 == 0) {
        // Child Process:
        doFib(n - 2, false);
    } else {
        // Parent Process: wait for the termination of child process
        waitpid(child1, &status1, 0);
        waitpid(child2, &status2, 0);
        if (WIFEXITED(status1) && WIFEXITED(status2)) {
            if (doPrint == true) {
                printf("%d\n", WEXITSTATUS(status1) + WEXITSTATUS(status2));
                return ;
            } else {
                // printf("%d %d\n", n, WEXITSTATUS(status1) + WEXITSTATUS(status2));
                exit(WEXITSTATUS(status1) + WEXITSTATUS(status2));
            }
        }
    }
}
