/**##############################################################
## MODULE: infinite.c
## VERSION: 1.0 
## SINCE: 2013-09-14
## AUTHOR: Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
## DESCRIPTION: 
##      
#################################################################
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/

#include <stdio.h>

int main() {

    while(1) {
        printf("sb\n");
        sleep(1);
    }

}
