/**
* @file macros.c 
* @version 1.0
* @since 2013-03-13
* @author Jimmy Lin (u5223173) - u5223173@uds.anu.edu.au
*
* Edited by MacVim
* Info auto-generated by Snippet 
* */

#include <stdio.h>
#define getMinimum(x,y) x<y?x:y

int main()
{
    int x = 111;
    int y = 10;
    printf("%d \n", getMinimum(x,y));


}
