package visitors;
import types.*;
/** 
* @module InOrderVisitor.java
* @version 1.0 
* @since 2013-04-30
* @author Jimmy Lin (u5223173) - u5223173@uds.anu.edu.au
* 
* Edited by MacVim
* Class Info auto-generated by Snippet 
*/
public class InOrderVisitor implements Visitor {
    // store string information for the result
    // organised by in-order sequence.
    private String result = "";
    public String getResult() { return this.result; }

    // public constructor 
    public InOrderVisitor () { } 

    public void visitConstant (Constant constant) {
        this.result +=  constant.toString() ;
        
    }

    public void visitMultiplication (Multiplication mult) {
        // in-order sequence
        this.result += "(";
       mult.getLeft().accept(this);
       // note that we do not necessarily provide parentheses
       // for the multiplication.
       this.result += " * ";
       mult.getRight().accept(this);
       this.result += ")";
    }

    public void visitAddition (Addition add) {
        // in-order sequence, first visit the left
        // expression and then present information 
        // on itself and finally the right-side node.
        this.result += "(";
        add.getLeft().accept(this);
        this.result += " + ";
        add.getRight().accept(this);
        this.result += ")";
    }

}
