/*##############################################################
## MODULE: Bidding.java
## VERSION: 1.0 
## SINCE: 2014-01-14
## AUTHOR: 
##         JIMMY LIN (xl5224) - JimmyLin@utexas.edu  
##
## DESCRIPTION: 
##    Algorithm Assignment #1: BIDDING SYSTEM
##    We implement the bidding-item stable matching by using
## Brute-Force algorithm.
## 
#################################################################
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.IOException;
import java.util.ArrayList;

// ****************************************************************
// Item data structure
class Item {
    // fields characterizing item
    int id;  
    int quality;  
    int price;  // unit: cents

    int highest_bid_id = -1;  
    int highest_bid_price = -1;  

    static int id_count;  // as id assigner

    // constructor for item class
    Item (int quality, int price) {
        this.id = id_count ++;
        this.quality = quality;
        this.price = price;  
    }
    public String toString () {
        String str = "bid: " + this.quality + "," + this.price;
        return str;
    }
}

// ****************************************************************
// Bid data structure
class Bid {
    int type;
    int bid_id;

    static int id_count;
    Bid (int type) {
        this.type = type;
        this.bid_id = Bid.id_count++;
    }
}

class SingleItemBid extends Bid {
    int item_id;
    int offer;

    SingleItemBid (int offer, int item_id) {
        super(1);
        this.offer = offer;
        this.item_id = item_id;
    }
    int getWeight () {
        // System.out.println(this.offer);
        return this.offer;
    }
}
class LinearBid extends Bid {
    int intercept;
    int slope;
    LinearBid (int intercept, int slope) {
        super(2);
        this.intercept = intercept;
        this.slope = slope;
    }
    int getWeight (int quality) {
        int weight = quality * this.slope + this.intercept;
        // System.out.println(weight);
        return weight;
    }
}
// ****************************************************************

class Bidding {
    static int highest_weight;
    public static void main (String [] args) throws IOException {
        BufferedReader reader = new BufferedReader(new
                InputStreamReader (System.in));

        // parse the number of items
        int n = Integer.parseInt(reader.readLine());
        // System.out.println("number of items: " + n);

        // create and parse item array
        Item [] items = new Item [n];
        String line = null;
        for (int i = 0; i < n; i ++) {
            line = reader.readLine();
            String [] item_infos = line.split(" ");
            int tmp_quality = Integer.parseInt(item_infos[0]);
            int tmp_price = Integer.parseInt(item_infos[1]);
            items[i] = new Item (tmp_quality, tmp_price);
            // System.out.println(items[i].toString());
        }

        // create and parse bidding arraylist
        ArrayList<Bid> bids = new ArrayList<Bid> ();
        while ((line = reader.readLine()) != null) {
            String [] bidding_infos = line.split(" ");
            int type = Integer.parseInt(bidding_infos[0]);
            if (type == 1) { // single-item bid
                int tmp_price = Integer.parseInt(bidding_infos[1]);
                int tmp_id = Integer.parseInt(bidding_infos[2]);
                bids.add (new SingleItemBid(tmp_price, tmp_id));
                // System.out.println("1 " + tmp_id + ", " + tmp_price);
            } else if (type == 2) { // linear bid
                int intercept = Integer.parseInt(bidding_infos[1]);
                int slope = Integer.parseInt(bidding_infos[2]);
                bids.add (new LinearBid(intercept, slope));
                // System.out.println("2 " + intercept + ", " + slope);
            } else if (type == 3) { // for summary
                int highest_weight = 0;
                int [] highest_weight_assignment = new int [n];
                int nBids = bids.size();
                int [] assignment = new int [n];
                // initial assignment
                for (int i = 0; i < n; i ++) {
                    assignment[i] = -1;  // retained by seller  
                }

                for (long count = 0; count < Math.pow(nBids+1, n); count ++) {
                    // instantiate assignment
                    for (int i = 0; i < n; i ++) {
                        assignment[i] = (int) (count / ((int)Math.pow (nBids+1, i))
                            % (nBids+1)) - 1;
                    }
                    // validate: remove duplicate bidding
                    int [] existingBids = new int [nBids];
                    for (int i = 0; i < nBids; i ++) {
                        existingBids[i] = 0;
                    }
                    boolean isValid = true;
                    for (int i = 0; i < n; i ++) {
                        if (assignment[i] == -1) {
                            continue;
                        } else if (existingBids[assignment[i]] > 0) {
                            // one bid cannot support two items
                            isValid = false;
                            break;
                        } else if (bids.get(assignment[i]).type == 1
                           && ((SingleItemBid) bids.get(assignment[i])).item_id != i) {
                            // single-item bid only valid for one item
                            isValid = false;
                            break;
                        } else {
                            existingBids[assignment[i]] ++;
                        }
                    }
                    if (!isValid) { 
                        continue;  // deal with next assignment if invalid
                    }
                    // compute weight of valid assignment
                    int tmp_weight = 0;
                    for (int i = 0; i < n; i ++) {
                        if (assignment[i] == -1) {
                            tmp_weight += items[i].price;
                            continue;
                        }
                        if (bids.get(assignment[i]).type == 1) {
                            tmp_weight += ((SingleItemBid)
                                    bids.get(assignment[i])).getWeight();
                        } else if (bids.get(assignment[i]).type == 2) {
                            tmp_weight += ((LinearBid)
                                    bids.get(assignment[i])).getWeight(items[i].quality);
                        }
                    }
                    // update the maximum assignment if it is
                    if (tmp_weight > highest_weight) {
                        highest_weight = tmp_weight;
                        for (int j = 0; j < n; j ++) {
                            highest_weight_assignment[j] = assignment[j];
                        }
                    }
                }
                // output
                String summary = Integer.toString (highest_weight);
                for (int i = 0; i < n; i ++) {
                    summary += " " + Integer.toString (
                            highest_weight_assignment[i]);
                }
                System.out.println(summary);
            } 
        }
    }
}
