''' 
    Filename:   draw.py    
    Version:    1.0
    Since:      2013-04-21
    Author: 
        Jimmy Lin (u5223173) - u5223173@uds.anu.edu.au
        
    Edited by MacVim
    Documentation auto-generated by Snippet 
'''
import pylab as pl
import numpy as np

pl.rcParams.update({'font.size': 18})

def figure1():
    x = range(1,34)
    y = []
    for each in x:
        temp = 0.001*(each-17)**2 + 0.04
        y.append(temp)

    pl.plot(x,y,'r-')
    pl.title('Relationship of error rate and k')
    pl.xlabel('value of k')
    pl.ylabel('error rate')

def figure2():
    x1 = [1.2,1.1,1.3,1.1,1.2,1.3,1.3] 
    y1 = [1.2,2.5,1.3,2.7,1.1,1.8,0.9]
    x2 = [0,0,4,4,2,2]
    y2 = [0,4,0,4,4,0]
    x3 = [2]
    y3 = [2]
    x4 = [2.9,3.0,3.1,3.0,3.0,2.9,3.1]
    y4 = [1.2,2.5,1.3,2.7,1.1,1.8,0.9]
    pl.plot(x1,y1,'ro',label="class A")
    pl.plot(x2,y2,'wo')
    pl.plot(x4,y4,'bx',label="class B",ms=10)
    pl.plot(x3,y3,'g*',label="test data",ms=10)

def figure3():
    x1 = [1.2,1.1,1.3,1.1,1.2,1.3,1.3,0.5,0.6,0.7] 
    y1 = [1.2,2.5,1.3,2.7,1.1,1.8,0.9,2.0,1.5,0.5]
    x2 = [0,0,4,4,2,2]
    y2 = [0,4,0,4,4,0]
    x3 = [2]
    y3 = [2]
    x4 = [2.9,3.0,3.1,3.0,3.0,2.9,3.1,2.3,2.2,2.2]
    y4 = [1.2,2.5,1.3,2.7,1.1,1.8,0.9,2.0,2.4,1.7]
    pl.plot(x1,y1,'ro',label="class A")
    pl.plot(x2,y2,'wo')
    pl.plot(x4,y4,'bx',label="class B",ms=10)
    pl.plot(x3,y3,'g*',label="test data",ms=10)

def figure4():
    x1 = [1,1,3,3,2.7,1.3,1.3,2.7]
    y1 = [1,3,3,1,2.7,1.3,2.7,1.3]
    x2 = [0,0,4,4,2,2]
    y2 = [0,4,0,4,4,0]
    x3 = [2]
    y3 = [2]
    x4 = [2.2,2.4,1.8,1.7]
    y4 = [2.3,1.5,2.5,1.6]
    pl.plot(x1,y1,'ro',label="class A")
    pl.plot(x2,y2,'wo')
    pl.plot(x4,y4,'bx',label="class B",ms=10)
    pl.plot(x3,y3,'g*',label="test data",ms=10)

def figure5():
    x1 = [1,1,3,3,2.7,1.3,1.3,2.7,2.7,2.8,1.2,1.3]
    y1 = [1,3,3,1,2.7,1.3,2.7,1.3,2.7,2.6,3.2,2.0]
    x2 = [0,0,4,4,2,2]
    y2 = [0,4,0,4,4,0]
    x3 = [2]
    y3 = [2]
    x4 = [2.2,2.4,1.8,1.7,2.1,2.3,1.9,1.8,2.2]
    y4 = [2.3,1.5,2.5,1.6,1.9,1.9,2.0,2.1,2.3]
    pl.plot(x1,y1,'ro',label="class A")
    pl.plot(x2,y2,'wo')
    pl.plot(x4,y4,'bx',label="class B",ms=10)
    pl.plot(x3,y3,'g*',label="test data",ms=10)

def main():
    #figure1()
    #figure2()
    figure3()
    #figure4()
    #figure5()
    pl.legend()
    pl.draw()
    pl.show()

main()
