all:
	cd digit ; make
	cd part1a ; make
	cd part1b ; make
	cd part2 ; make
	cd part3a ; make
	cd part3b ; make

clean:
	rm -f part*/*.o
	rm -f part*/sofm_wrap.c

allclean: clean
	rm -f digit/digit
	rm -f part*/*.so
	rm -f part*/*sofm
