%% Homework 03: LQ Factorization
% Copyright 2014 The University of Texas at Austin
%
% For licensing information see
%                http://www.cs.utexas.edu/users/flame/license.html 
%                                                                                 
% Programmed by: Jimmy Lin
%                jimmylin@utexas.edu
function [ A_out, L_out, Q_out ] = LG_CGS_unb( A, L, Q )
  [ AT, ...
    AB ] = FLA_Part_2x1( A, ...
                         0, 'FLA_TOP' );
  [ LTL, LTR, ...
    LBL, LBR ] = FLA_Part_2x2( L, ...
                               0, 0, 'FLA_TL' );
  [ QT, ...
    QB ] = FLA_Part_2x1( Q, ...
                         0, 'FLA_TOP' );
  while ( size( AT, 1 ) < size( A, 1 ) )
    [ A0, ...
      a1t, ...
      A2 ] = FLA_Repart_2x1_to_3x1( AT, ...
                                    AB, ...
                                    1, 'FLA_BOTTOM' );
    [ L00,  l01,      L02,  ...
      l10t, lambda11, l12t, ...
      L20,  l21,      L22 ] = FLA_Repart_2x2_to_3x3( LTL, LTR, ...
                                                     LBL, LBR, ...
                                                     1, 1, 'FLA_BR' );
    [ Q0, ...
      q1t, ...
      Q2 ] = FLA_Repart_2x1_to_3x1( QT, ...
                                    QB, ...
                                    1, 'FLA_BOTTOM' );
    %------------------------------------------------------------%
    l10t = a1t * Q0';
    temp = a1t - l10t * Q0;
    lambda11 = norm(temp, 2);
    q1t = temp / lambda11;
    %------------------------------------------------------------%
    [ AT, ...
      AB ] = FLA_Cont_with_3x1_to_2x1( A0, ...
                                       a1t, ...
                                       A2, ...
                                       'FLA_TOP' );
    [ LTL, LTR, ...
      LBL, LBR ] = FLA_Cont_with_3x3_to_2x2( L00,  l01,      L02,  ...
                                             l10t, lambda11, l12t, ...
                                             L20,  l21,      L22, ...
                                             'FLA_TL' );
    [ QT, ...
      QB ] = FLA_Cont_with_3x1_to_2x1( Q0, ...
                                       q1t, ...
                                       Q2, ...
                                       'FLA_TOP' );
  end
  A_out = [ AT
            AB ];
  L_out = [ LTL, LTR
            LBL, LBR ];
  Q_out = [ QT
            QB ];
return
