%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Project 01: Householder QR Transformation
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Copyright 2014 The University of Texas at Austin
%
% For licensing information see
%                http://www.cs.utexas.edu/users/flame/license.html 
%                                                                                 
% Programmed by: Jimmy Lin
%                jimmylin@utexas.edu

function [ A_out, T_out ] = HQR_unb ( A, T )

  [ ATL, ATR, ...
    ABL, ABR ] = FLA_Part_2x2( A, ...
                               0, 0, 'FLA_TL' );

  [ TT, ...
    TB ] = FLA_Part_2x1( T, ...
                         0, 'FLA_TOP' );

  while ( size( ATL, 1 ) < size( A, 1 ) )

    [ A00,  a01,     A02,  ...
      a10t, alpha11, a12t, ...
      A20,  a21,     A22 ] = FLA_Repart_2x2_to_3x3( ATL, ATR, ...
                                                    ABL, ABR, ...
                                                    1, 1, 'FLA_BR' );
    [ T0, ...
      t1t, ...
      T2 ] = FLA_Repart_2x1_to_3x1( TT, ...
                                    TB, ...
                                    1, 'FLA_BOTTOM' );
    %------------------------------------------------------------%
    
    [ alpha11, a21, t1t ] = Housev( alpha11, a21 );
    w12t = (a12t + a21' * A22) / t1t;
    a12t = a12t - w12t;
    A22 = A22 - a21 * w12t;

    %------------------------------------------------------------%

    [ ATL, ATR, ...
      ABL, ABR ] = FLA_Cont_with_3x3_to_2x2( A00,  a01,     A02,  ...
                                             a10t, alpha11, a12t, ...
                                             A20,  a21,     A22, ...
                                             'FLA_TL' );
    [ TT, ...
      TB ] = FLA_Cont_with_3x1_to_2x1( T0, ...
                                       t1t, ...
                                       T2, ...
                                       'FLA_TOP' );
  end

  A_out = [ ATL, ATR
            ABL, ABR ];
  T_out = [ TT
            TB ];
return
