''' 
    Filename:   tut02.py    
    Version:    1.0
    Since:      2013-03-21
    Author: 
        Jimmy Lin (u5223173) - u5223173@uds.anu.edu.au
         
    Edited by MacVim
    Documentation auto-generated by Snippet 
'''

def main():
    dataFilePath = "./Canberra-Houses.txt"
    dataFile = open( dataFilePath )
    for i in range(0, len(dataFile)):
        if i == 0:
            continue
        else:




main()
