############################################################
##    FILENAME:   Logging.py
##    VERSION:    1.0
##    SINCE:      2014-04-15
##    AUTHOR:
##        Jimmy Lin (xl5224) - JimmyLin@utexas.edu
##
############################################################
##    Edited by MacVim
##    Documentation auto-generated by Snippet
############################################################


MASTER_LOG_HEADER = "[MASTER] ";
SERVER_LOG_HEADER = "[SERVER #%d] ";
CLIENT_LOG_HEADER = "[CLIENT #%d] ";

CLIENT_LOG_FILENAME = "logs/Client%d.txt";
SERVER_LOG_FILENAME = "logs/Server%d.txt";
Master_LOG_FILENAME = "logs/Master.txt";
RESULT_FILENAME = "logs/result.txt";
