/*##############################################################
## MODULE: Acceptor.java
## VERSION: 1.0
## SINCE: 2014-04-02
## AUTHOR: 
##         JIMMY LIN (xl5224) - JimmyLin@utexas.edu  
##
## DESCRIPTION: 
##      
################################################################# 
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/

import java.util.concurrent.LinkedBlockingQueue;
import java.util.HashSet;

class Acceptor implements Runnable {
        LinkedBlockingQueue<String> queue = null;
        // ballotNum: the current adopted ballot number
        int ballot_num;
        // accepted: set of accepted ballots
        HashSet<String> accepted;
        
        InetAddress localhost;
        int serverID;

        public Acceptor(LinkedBlockingQueue<String> queue, int id) {
            this.queue = queue;
        }

        public void run() {
            localhost = InetAddress.getLocalHost();
            // while true
            while (true) {
                // STEP ONE: receive messages from queue
                String msg;
                try {
                    msg = queue.take();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

                // STEP TWO: decode
                String [] msgParts = msg.split(MESSAGE_SEP);
                String title = msgParts[TITLE_IDX];
                String content = msgParts[CONTENT_IDX];
                
                String [] conts = content.split(CONTENT_SEP);

                // if message is a p1a
                if (title.equals(P1A_TITLE)) {
                    int lambda = Integer.parseInt(conts[0]); // leader id
                    int b = Integer.parseInt(conts[1]);
                    // if the given ballot number is greater than the current one, then adopt it
                    if (b > ballot_num) {
                        ballot_num = b;
                    }
                    // send a p1b in response with identifier, its current
                    // ballot number, and all accepted pvalue
                    
                    int port = SERVER_PORT_BASE + lambda;
                    String accepted_str = "";
                    for (String pvalue : accepted) {
                        accepted_str += pvalue + PVALUE_SEP;
                    }
                    accepted_str = accepted_str.substring(0, accepted_str.length()-PVALUE_SEP.length());
                    String p1b_content = String.format(P1B_CONTENT, serverID, ballot_num, accepted_str);
                    String p1b_response = String.format(MESSAGE, SERVER_TYPE, serverID, LEADER_TYPE, lambda, 
                            P1B_TITLE, p1b_content);
                    send (localhost, port, p1b_response, logHeader);
                }
                // if message is a p2a
                else if (title.equals(P2A_TITLE)) {
                    int lambda = Integer.parseInt(conts[0]); // leader id
                    String pvalue = conts[1];
                    // if the given ballot number is greater than or equal to the current one
                    if (b >= ballot_num) {
                        // adopt that ballot number and accept the ballot
                        ballot_num = b;
                        accepted.add(pvalue);
                    } 
                    // send a p2b in response with the current ballot number
                    int port = SERVER_PORT_BASE + lambda;
                    String p2b_content = String.format(P2B_CONTENT, serverID, ballot_num);
                    String p2b_response = String.format(Message, SERVER_TYPE, serverID, LEADER_TYPE, lambda, 
                           P2B_TITLE, P2B_content);
                    send (localhost, port, p2b_response, logHeader);
                }
            }
        }
    }
