############################################################
##    FILENAME:   Protocol.py    
##    VERSION:    1.0
##    SINCE:      2014-04-15
##    AUTHOR: 
##        Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
##
############################################################
##    Edited by MacVim
##    Documentation auto-generated by Snippet 
############################################################

# BUFFER SIZE
BUFFER_SIZE = 1024

# NODE TYPE SPECIFICATION
MASTER_TYPE = "MASTER"
CLIENT_TYPE = "CLIENT"
SERVER_TYPE = "SERVER"

# NETWORK PORT BASE
CLIENT_PORT_BASE = 8100+63;
SERVER_PORT_BASE = 8510+83; 
MASTER_PORT = 8070;

# PROTOCOL DESIGN
SENDER_TYPE_IDX = 0;
SENDER_INDEX_IDX = 1;
RECEIVER_TYPE_IDX = 2;
RECEIVER_INDEX_IDX = 3;
TITLE_IDX = 4;
CONTENT_IDX = 5;

# MESSAGE FORMAT
MESSAGE_SEP = ",";
MESSAGE = "%s" + MESSAGE_SEP + "%d" + MESSAGE_SEP +"%s" + MESSAGE_SEP \
        +"%d" + MESSAGE_SEP +"%s" + MESSAGE_SEP +"%s";

# TITLES
EXIT_TITLE = "EXIT"
JOIN_SERVER_ACK_TITLE = "JOIN_SERVER_ACK"
JOIN_CLIENT_ACK_TITLE = "JOIN_CLIENT_ACK"
PAUSE_TITLE = "PAUSE"
PAUSE_ACK_TITLE = "PAUSE_ACK"
RESTART_TITLE = "RESTART"
RESTART_ACK_TITLE = "RESTART_ACK"

RETIRE_REQUEST_TITLE = "PLEASE_RETIRE"

# CONTENT
EMPTY_CONTENT = "EMPTY"
