/*##############################################################
## MODULE: Server.java
## VERSION: 1.0 
## SINCE: 2014-03-30
## AUTHOR: 
##     JIMMY LIN (xl5224) - JimmyLin@utexas.edu  
##
## DESCRIPTION: 
##     Server Class of PAXOS consensus algorithm
## 
#################################################################
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/

import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.InetAddress;

class Server {
    /* Protocol configuration */
    final static int CLIENT_PORT_BASE = 8000;
    final static int SERVER_PORT_BASE = 8200; 

    static int serverID;

    public static void main (String [] args) throws IOException {
        // parse the server id assigned by master
        serverID = Integer.parseInt(args[1]);
        // construct stable server socket
        ServerSocket listener = new ServerSocket(SERVER_PORT_BASE+serverID);
        try {
            while (true) {
                Socket socket = listener.accept();
                try {
                   BufferedReader in = new BufferedReader(new
                           InputStreamReader(socket.getInputStream()));
                   // channel is established
                   // TODO: process received message

                } finally socket.close();
            }
        } finally {
            listener.close();
        }
    }
}
