/*##############################################################
## MODULE: Util.java
## VERSION: 1.0 
## SINCE: 2014-03-31
## AUTHOR: 
##         JIMMY LIN (xl5224) - JimmyLin@utexas.edu  
##
## DESCRIPTION: 
##      
#################################################################
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/

import java.io.IOException;
import java.net.Socket;
import java.net.InetAddress;
import java.io.PrintWriter;

class Util implements Protocol, Logging {
    /* get client port given the clientIndex */
    public static int getClientPort (int clientIndex) { return 0; }
    public static int getServerPort (int clientIndex) { return 0; }

    /* Send util functions */
    public static void send (InetAddress host, int port, String message, 
            String HEADER) throws IOException { 
        // set null header as empty string
        if (HEADER == null) HEADER = "";
        // establish temporary socket connection
        Socket socket = new Socket(host, port);
        try {
            PrintWriter out =
                new PrintWriter(socket.getOutputStream(), true);
            out.println(message);
            System.out.println(HEADER + "Message sent: " + message);
        } finally {
            socket.close();
        }
    }

    /* Send all messages */
    public static void sendAll (InetAddress host, int port, String [] messages,
            String HEADER) throws IOException {
        // set null header as empty string
        if (HEADER == null) HEADER = "";
        // establish temporary socket connection
        Socket socket = new Socket(host, port);
        try {
            PrintWriter out =
                new PrintWriter(socket.getOutputStream(), true);
            for (int i = 0; i < messages.length; i ++) {
                out.println(messages[i]);
                System.out.println(HEADER + "Message sent: " + messages[i]);
            }
        } finally {
            socket.close();
        }

    }

}
