/*##############################################################
## MODULE: Util.java
## VERSION: 1.0 
## SINCE: 2014-03-31
## AUTHOR: 
##         JIMMY LIN (xl5224) - JimmyLin@utexas.edu  
##
## DESCRIPTION: 
##      
#################################################################
## Edited by MacVim
## Class Info auto-generated by Snippet 
################################################################*/

import java.io.IOException;
import java.net.Socket;
import java.net.InetAddress;
import java.io.PrintWriter;
class Util {
    /* LOG HEADERS */
    final static String MASTER_LOG_HEADER = "[MASTER] ";
    final static String SERVER_LOG_HEADER = "[SERVER #%d] ";
    final static String CLIENT_LOG_HEADER = "[CLIENT #%d] ";

    /* LOG FILENAME */
    final static String CLIENT_LOG_FILENAME = "logs/Client%d.txt";
    final static String SERVER_LOG_FILENAME = "logs/Server%d.txt";

    public static void send (InetAddress host, int port, String message, 
            String HEADER) throws IOException { 
        if (HEADER == null) HEADER = "";
        Socket socket = new Socket(host, port);
        try {
            PrintWriter out =
                new PrintWriter(socket.getOutputStream(), true);
            out.println(message);
            System.out.println(HEADER + "Message sent: " + message);
        } finally {
            socket.close();
        }
    }
}
